### ISSUE TITLE
Check failed: false Unknown filler name: identity

### ISSUE THREAD

**Issue by mahfuj9346449** [thuml/transfer-caffe#10]
When I run JAN with adversarial layer, I got the following error. Could you please help to figure out the problem?

F1005 09:04:07.176527 32676 filler.hpp:312] Check failed: false Unknown filler name: identity
*** Check failure stack trace: ***
    @     0x7ff27ce5a5cd  google::LogMessage::Fail()
    @     0x7ff27ce5c433  google::LogMessage::SendToLog()
    @     0x7ff27ce5a15b  google::LogMessage::Flush()
    @     0x7ff27ce5ce1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff27d4b2569  caffe::GetFiller<>()
    @     0x7ff27d58efb3  caffe::InnerProductLayer<>::LayerSetUp()
    @     0x7ff27d63d3b2  caffe::Net<>::Init()
    @     0x7ff27d63ec41  caffe::Net<>::Net()
    @     0x7ff27d606f5a  caffe::Solver<>::InitTrainNet()
    @     0x7ff27d608257  caffe::Solver<>::Init()
    @     0x7ff27d6085fa  caffe::Solver<>::Solver()
    @     0x7ff27d628ae3  caffe::Creator_SGDSolver<>()
    @           0x40b152  train()
    @           0x407878  main
    @     0x7ff27b811830  __libc_start_main
    @           0x408289  _start
    @              (nil)  (unknown)

**Comment by caozhangjie** [comment]
This repository is updated and we only leave DAN in this repository. The newest JAN code is in https://github.com/thuml/Xlearn.
