### ISSUE TITLE
Negative MMD loss

### ISSUE THREAD

**Issue by insmod-he** [thuml/transfer-caffe#3]
Hi,thuml:
    Thanks for your great work. I am new to this field and recently I tried to run the DAN model on my task. However, I find that the mmd loss sometimes got a negative value. Is that normal? 
  I even tied get mmd loss between two same feature, and it always got a negative value. I think it should be 0. Am I right?

**Comment by caozhangjie** [comment]
It's normal to get a negative value. As shown in our paper, we implement a linear-time unbiased estimate of the kernel mean embedding to enable scalable training. Thus it can be negative value while standard MMD cannot get a negative value.

**Comment by insmod-he** [comment]
Thanks a lot. That's really helpful for me.
