### ISSUE TITLE
JMMD loss value is zero!

### ISSUE THREAD

**Issue by swamiviv** [thuml/transfer-caffe#5]
I am running the J-MMD loss layer with a different dataset and the fc7_mmd_loss and label_mmd_loss are printed as zero throughout the training. I wonder what is wrong there. Any help to debug this will be appreciated. The softmax_loss works correctly so I think there is nothing wrong with the way I am providing the data.

**Comment by zhuhan1236** [comment]
Sorry that the computation of mmd_loss value in forward stage is not implemented. But the effectiveness won't be affected.
